name = "bare_runtime"
description = "Minimal Ada/SPARK run-time for embedded or other restricted targets"
version = "14.0.0-dev"

authors = ["AdaCore"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
tags = ["embedded", "runtime"]
website = "https://github.com/Fabien-Chouteau/bare_runtime"

[configuration]
generate_gpr = false
generate_c = false

[configuration.variables]
LCH_Print_Info = { type = "Boolean", default = false }
LCH_Reset = { type = "Boolean", default = false }

[[depends-on]]
gnat = "^14"
