name = "bare_runtime"
description = "Minimal Ada/SPARK run-time for embedded or other restricted targets"
version = "14.0.0-dev"

maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[configuration]
generate_gpr = false
generate_c = false

[configuration.variables]
LCH_Print_Info = { type = "Boolean", default = false }
LCH_Reset = { type = "Boolean", default = false }

[[depends-on]]
gnat = "^14"
